apiVersion: apps/v1
kind: Deployment
metadata:
  name: codo-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codo-demo
  template:
    metadata:
      labels:
        app: codo-demo
    spec:
      containers:
      - name: codo-demo
        image: harbor-k8s.shinezone.com/ops/codo-demo:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
          - name: demonginx
            mountPath: /etc/nginx/conf.d/
      volumes:
        - name: demonginx
          configMap:
            name: demo-nginx-conf  # kubectl create configmap demo-nginx-conf --from-file=./nginx_demo.conf -n qa

---
apiVersion: v1
kind: Service
metadata:
  name: codo-demo
  labels:
    app: codo-demo
spec:
  selector:
    app: codo-demo
  #type: NodePort
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: codo-demo-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: <DOMAIN>
    http:
      paths:
      - path:
        backend:
          serviceName: codo-demo
          servicePort: 80